window.BIVA2_POPULATIONS = [
  {
    "code": 101,
    "n": 354,
    "r_h_mean": 298.6,
    "r_h_sd": 43.2,
    "xc_h_mean": 30.8,
    "xc_h_sd": 7.3,
    "correlation": 0.47,
    "sex": "M",
    "legend": "Males, White, reference adults, Italy",
    "country": "Italy",
    "age": "Adults",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "Piccoli A et al, Am J Clin Nutr 61:269-270,1995. (see BIVAguide, ref. 12)",
    "source": "confidence"
  },
  {
    "code": 102,
    "n": 372,
    "r_h_mean": 371.9,
    "r_h_sd": 49,
    "xc_h_mean": 34.4,
    "xc_h_sd": 7.7,
    "correlation": 0.41,
    "sex": "F",
    "legend": "Females, White, reference adults, Italy",
    "country": "Italy",
    "age": "Adults",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "Piccoli A et al, Am J Clin Nutr 61:269-270,1995. (see BIVAguide, ref. 12)",
    "source": "confidence"
  },
  {
    "code": 103,
    "n": 680,
    "r_h_mean": 292.6,
    "r_h_sd": 40.6,
    "xc_h_mean": 26.3,
    "xc_h_sd": 5.8,
    "correlation": 0.32,
    "sex": "M",
    "legend": "Males, White, pre-HD, stable",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A, Kidney Int 53:1036-1043, 1998. (see BIVAguide ref 17)",
    "source": "confidence"
  },
  {
    "code": 104,
    "n": 680,
    "r_h_mean": 343,
    "r_h_sd": 47.1,
    "xc_h_mean": 35.4,
    "xc_h_sd": 8,
    "correlation": 0.42,
    "sex": "M",
    "legend": "Males, White, post-HD, stable",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A, Kidney Int 53:1036-1043, 1998. (see BIVAguide ref 17)",
    "source": "confidence"
  },
  {
    "code": 105,
    "n": 118,
    "r_h_mean": 302,
    "r_h_sd": 46,
    "xc_h_mean": 23.8,
    "xc_h_sd": 8,
    "correlation": 0.31,
    "sex": "M",
    "legend": "Males, White, pre-HD, unstable",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A, Kidney Int 53:1036-1043, 1998. (see BIVAguide ref 17)",
    "source": "confidence"
  },
  {
    "code": 106,
    "n": 118,
    "r_h_mean": 351.3,
    "r_h_sd": 50.4,
    "xc_h_mean": 30.6,
    "xc_h_sd": 10.6,
    "correlation": 0.36,
    "sex": "M",
    "legend": "Males, White, post-HD, unstable",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A, Kidney Int 53:1036-1043, 1998. (see BIVAguide ref 17)",
    "source": "confidence"
  },
  {
    "code": 107,
    "n": 436,
    "r_h_mean": 353.6,
    "r_h_sd": 44.9,
    "xc_h_mean": 29.3,
    "xc_h_sd": 7.3,
    "correlation": 0.38,
    "sex": "F",
    "legend": "Females, White, pre-HD, stable",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A, Kidney Int 53:1036-1043, 1998. (see BIVAguide ref 17)",
    "source": "confidence"
  },
  {
    "code": 108,
    "n": 436,
    "r_h_mean": 418.5,
    "r_h_sd": 53.8,
    "xc_h_mean": 39.7,
    "xc_h_sd": 10,
    "correlation": 0.42,
    "sex": "F",
    "legend": "Females, White, post-HD, stable",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A, Kidney Int 53:1036-1043, 1998. (see BIVAguide ref 17)",
    "source": "confidence"
  },
  {
    "code": 109,
    "n": 133,
    "r_h_mean": 371.5,
    "r_h_sd": 61.1,
    "xc_h_mean": 27.6,
    "xc_h_sd": 9.1,
    "correlation": 0.28,
    "sex": "F",
    "legend": "Females, White, pre-HD, unstable",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A, Kidney Int 53:1036-1043, 1998. (see BIVAguide ref 17)",
    "source": "confidence"
  },
  {
    "code": 110,
    "n": 133,
    "r_h_mean": 433.2,
    "r_h_sd": 67.6,
    "xc_h_mean": 36.5,
    "xc_h_sd": 11.8,
    "correlation": 0.33,
    "sex": "F",
    "legend": "Females, White, post-HD, unstable",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A, Kidney Int 53:1036-1043, 1998. (see BIVAguide ref 17)",
    "source": "confidence"
  },
  {
    "code": 111,
    "n": 25,
    "r_h_mean": 238,
    "r_h_sd": 48.2,
    "xc_h_mean": 13.9,
    "xc_h_sd": 3.4,
    "correlation": 0.36,
    "sex": "M",
    "legend": "Males, White, with edema",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see BIVAguide, ref. 16)",
    "source": "confidence"
  },
  {
    "code": 112,
    "n": 25,
    "r_h_mean": 290.8,
    "r_h_sd": 59.8,
    "xc_h_mean": 15.2,
    "xc_h_sd": 4.6,
    "correlation": 0.61,
    "sex": "F",
    "legend": "Females, White, with edema",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see BIVAguide, ref. 16)",
    "source": "confidence"
  },
  {
    "code": 113,
    "n": 169,
    "r_h_mean": 234.6,
    "r_h_sd": 28.6,
    "xc_h_mean": 25.3,
    "xc_h_sd": 4.9,
    "correlation": 0.52,
    "sex": "M",
    "legend": "Males, White, Obesity I-III (31< BMI < 67)",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see BIVAguide, ref. 16)",
    "source": "confidence"
  },
  {
    "code": 114,
    "n": 371,
    "r_h_mean": 299,
    "r_h_sd": 43.5,
    "xc_h_mean": 30.2,
    "xc_h_sd": 7.2,
    "correlation": 0.63,
    "sex": "F",
    "legend": "Females, White, Obesity I-III (31< BMI < 80)",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see BIVAguide, ref. 16)",
    "source": "confidence"
  },
  {
    "code": 115,
    "n": 18,
    "r_h_mean": 234.3,
    "r_h_sd": 27.9,
    "xc_h_mean": 24.6,
    "xc_h_sd": 4.6,
    "correlation": 0.861,
    "sex": "M",
    "legend": "Males, White, Obesity II-III (37< BMI < 50), pre-diet",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see BIVAguide, ref. 16)",
    "source": "confidence"
  },
  {
    "code": 116,
    "n": 18,
    "r_h_mean": 244.1,
    "r_h_sd": 27.7,
    "xc_h_mean": 25.3,
    "xc_h_sd": 4.4,
    "correlation": 0.493,
    "sex": "M",
    "legend": "Males, White, Obesity II-III,-10.9 Kg, post-diet",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see BIVAguide, ref. 16)",
    "source": "confidence"
  },
  {
    "code": 117,
    "n": 30,
    "r_h_mean": 308.3,
    "r_h_sd": 37.7,
    "xc_h_mean": 31.4,
    "xc_h_sd": 5.8,
    "correlation": 0.567,
    "sex": "F",
    "legend": "Females, White, Obesity III (40< BMI < 55), pre-diet",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see BIVAguide, ref. 16)",
    "source": "confidence"
  },
  {
    "code": 118,
    "n": 30,
    "r_h_mean": 305.2,
    "r_h_sd": 36.3,
    "xc_h_mean": 31.2,
    "xc_h_sd": 4.9,
    "correlation": 0.597,
    "sex": "F",
    "legend": "Females, White, Obesity III, -7.3 Kg, post-diet",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see BIVAguide, ref. 16)",
    "source": "confidence"
  },
  {
    "code": 119,
    "n": 13,
    "r_h_mean": 248.1,
    "r_h_sd": 24.9,
    "xc_h_mean": 23.2,
    "xc_h_sd": 5.1,
    "correlation": 0.091,
    "sex": "M",
    "legend": "Males, White, Obesity I-III (31< BMI < 41), pre-HD",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see BIVAguide, ref. 16)",
    "source": "confidence"
  },
  {
    "code": 120,
    "n": 13,
    "r_h_mean": 297.1,
    "r_h_sd": 35.5,
    "xc_h_mean": 31.7,
    "xc_h_sd": 7.2,
    "correlation": 0.262,
    "sex": "M",
    "legend": "Males, White, Obesity I-III, -3.6 Kg, post-HD",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see BIVAguide, ref. 16)",
    "source": "confidence"
  },
  {
    "code": 121,
    "n": 19,
    "r_h_mean": 325.9,
    "r_h_sd": 40.2,
    "xc_h_mean": 26.7,
    "xc_h_sd": 6.4,
    "correlation": 0.523,
    "sex": "F",
    "legend": "Females, White, Obesity I-II (31< BMI < 39), pre-HD",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see BIVAguide, ref. 16)",
    "source": "confidence"
  },
  {
    "code": 122,
    "n": 19,
    "r_h_mean": 387.8,
    "r_h_sd": 45.6,
    "xc_h_mean": 36,
    "xc_h_sd": 7.7,
    "correlation": 0.693,
    "sex": "F",
    "legend": "Females, White, Obesity I-II, -2.9 Kg, post-HD",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see BIVAguide, ref. 16)",
    "source": "confidence"
  },
  {
    "code": 123,
    "n": 56,
    "r_h_mean": 308,
    "r_h_sd": 49,
    "xc_h_mean": 31,
    "xc_h_sd": 6,
    "correlation": 0.76,
    "sex": "M",
    "legend": "Males, White, reference group matched by age and BMI",
    "country": "—",
    "age": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "Toso S et al, Nutition 16:120-124, 2000. (see BIVAguide, ref. 22)",
    "source": "confidence"
  },
  {
    "code": 124,
    "n": 33,
    "r_h_mean": 302,
    "r_h_sd": 49,
    "xc_h_mean": 25,
    "xc_h_sd": 6,
    "correlation": 0.14,
    "sex": "M",
    "legend": "Males, White, Lung cancer IIIB, age 67, BMI 25",
    "country": "—",
    "age": "67",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Toso S et al, Nutition 16:120-124, 2000. (see BIVAguide, ref. 22)",
    "source": "confidence"
  },
  {
    "code": 125,
    "n": 30,
    "r_h_mean": 314,
    "r_h_sd": 61,
    "xc_h_mean": 24,
    "xc_h_sd": 7,
    "correlation": 0.25,
    "sex": "M",
    "legend": "Males, White, Lung cancer IV, age 64, BMI 25",
    "country": "—",
    "age": "64",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Toso S et al, Nutition 16:120-124, 2000. (see BIVAguide, ref. 22)",
    "source": "confidence"
  },
  {
    "code": 200,
    "n": 653,
    "r_h_mean": 292.5,
    "r_h_sd": 33.8,
    "xc_h_mean": 40.3,
    "xc_h_sd": 6.2,
    "correlation": 0.56,
    "sex": "M",
    "legend": "Males, White, 19 BMI 25, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 201,
    "n": 193,
    "r_h_mean": 286.5,
    "r_h_sd": 29.5,
    "xc_h_mean": 42.7,
    "xc_h_sd": 5.5,
    "correlation": 0.58,
    "sex": "M",
    "legend": "Males, White, 19 BMI 25, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 202,
    "n": 151,
    "r_h_mean": 290.8,
    "r_h_sd": 35.5,
    "xc_h_mean": 41.1,
    "xc_h_sd": 6,
    "correlation": 0.75,
    "sex": "M",
    "legend": "Males, White, 19 BMI 25, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 203,
    "n": 115,
    "r_h_mean": 291.1,
    "r_h_sd": 32.4,
    "xc_h_mean": 39.9,
    "xc_h_sd": 5.8,
    "correlation": 0.69,
    "sex": "M",
    "legend": "Males, White, 19 BMI 25, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 204,
    "n": 97,
    "r_h_mean": 296.4,
    "r_h_sd": 37.4,
    "xc_h_mean": 37.9,
    "xc_h_sd": 6.3,
    "correlation": 0.67,
    "sex": "M",
    "legend": "Males, White, 19 BMI 25, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 205,
    "n": 97,
    "r_h_mean": 304.5,
    "r_h_sd": 33.8,
    "xc_h_mean": 37.2,
    "xc_h_sd": 6,
    "correlation": 0.6,
    "sex": "M",
    "legend": "Males, White, 19 BMI 25, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 206,
    "n": 919,
    "r_h_mean": 266.4,
    "r_h_sd": 29,
    "xc_h_mean": 36.6,
    "xc_h_sd": 5.8,
    "correlation": 0.55,
    "sex": "M",
    "legend": "Males, White, 25 BMI 30, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 207,
    "n": 128,
    "r_h_mean": 263.9,
    "r_h_sd": 27,
    "xc_h_mean": 40.1,
    "xc_h_sd": 5.6,
    "correlation": 0.62,
    "sex": "M",
    "legend": "Males, White, 25 BMI 30, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 208,
    "n": 193,
    "r_h_mean": 265.3,
    "r_h_sd": 27.6,
    "xc_h_mean": 38.8,
    "xc_h_sd": 5.1,
    "correlation": 0.74,
    "sex": "M",
    "legend": "Males, White, 25 BMI 30, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 209,
    "n": 188,
    "r_h_mean": 263.3,
    "r_h_sd": 27.9,
    "xc_h_mean": 37.4,
    "xc_h_sd": 5.3,
    "correlation": 0.61,
    "sex": "M",
    "legend": "Males, White, 25 BMI 30, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 210,
    "n": 180,
    "r_h_mean": 267.2,
    "r_h_sd": 28.6,
    "xc_h_mean": 35.4,
    "xc_h_sd": 4.8,
    "correlation": 0.66,
    "sex": "M",
    "legend": "Males, White, 25 BMI 30, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 211,
    "n": 230,
    "r_h_mean": 270.4,
    "r_h_sd": 32.5,
    "xc_h_mean": 33.1,
    "xc_h_sd": 5.3,
    "correlation": 0.64,
    "sex": "M",
    "legend": "Males, White, 25 BMI 30, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 212,
    "n": 369,
    "r_h_mean": 242.4,
    "r_h_sd": 25.6,
    "xc_h_mean": 33.1,
    "xc_h_sd": 5.1,
    "correlation": 0.52,
    "sex": "M",
    "legend": "Males, White, 30 BMI 35, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 213,
    "n": 36,
    "r_h_mean": 237.8,
    "r_h_sd": 23.4,
    "xc_h_mean": 35.8,
    "xc_h_sd": 4.9,
    "correlation": 0.72,
    "sex": "M",
    "legend": "Males, White, 30 BMI 35, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 214,
    "n": 62,
    "r_h_mean": 239.7,
    "r_h_sd": 27.5,
    "xc_h_mean": 34.7,
    "xc_h_sd": 4.4,
    "correlation": 0.68,
    "sex": "M",
    "legend": "Males, White, 30 BMI 35, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 215,
    "n": 71,
    "r_h_mean": 238.7,
    "r_h_sd": 25.6,
    "xc_h_mean": 33.9,
    "xc_h_sd": 5.3,
    "correlation": 0.66,
    "sex": "M",
    "legend": "Males, White, 30 BMI 35, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 216,
    "n": 89,
    "r_h_mean": 241.6,
    "r_h_sd": 22.4,
    "xc_h_mean": 32.3,
    "xc_h_sd": 4.7,
    "correlation": 0.41,
    "sex": "M",
    "legend": "Males, White, 30 BMI 35, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 217,
    "n": 111,
    "r_h_mean": 248.3,
    "r_h_sd": 26.8,
    "xc_h_mean": 31.5,
    "xc_h_sd": 5.1,
    "correlation": 0.6,
    "sex": "M",
    "legend": "Males, White, 30 BMI 35, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 218,
    "n": 1009,
    "r_h_mean": 383.9,
    "r_h_sd": 44.8,
    "xc_h_mean": 48.1,
    "xc_h_sd": 7.1,
    "correlation": 0.59,
    "sex": "F",
    "legend": "Females, White, 19 BMI 25, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 219,
    "n": 280,
    "r_h_mean": 378.4,
    "r_h_sd": 44,
    "xc_h_mean": 50.2,
    "xc_h_sd": 7.3,
    "correlation": 0.69,
    "sex": "F",
    "legend": "Females, White, 19 BMI 25, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 220,
    "n": 261,
    "r_h_mean": 370.7,
    "r_h_sd": 38.5,
    "xc_h_mean": 47.7,
    "xc_h_sd": 6.4,
    "correlation": 0.69,
    "sex": "F",
    "legend": "Females, White, 19 BMI 25, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 221,
    "n": 182,
    "r_h_mean": 386.6,
    "r_h_sd": 44,
    "xc_h_mean": 48.9,
    "xc_h_sd": 7.2,
    "correlation": 0.73,
    "sex": "F",
    "legend": "Females, White, 19 BMI 25, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 222,
    "n": 146,
    "r_h_mean": 393,
    "r_h_sd": 43.6,
    "xc_h_mean": 46.9,
    "xc_h_sd": 6.9,
    "correlation": 0.64,
    "sex": "F",
    "legend": "Females, White, 19 BMI 25, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 223,
    "n": 140,
    "r_h_mean": 406.1,
    "r_h_sd": 49.3,
    "xc_h_mean": 45,
    "xc_h_sd": 6.6,
    "correlation": 0.57,
    "sex": "F",
    "legend": "Females, White, 19 BMI 25, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 224,
    "n": 616,
    "r_h_mean": 355,
    "r_h_sd": 36.2,
    "xc_h_mean": 44.9,
    "xc_h_sd": 6.6,
    "correlation": 0.59,
    "sex": "F",
    "legend": "Females, White, 25 BMI 30, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 225,
    "n": 70,
    "r_h_mean": 353.2,
    "r_h_sd": 36.7,
    "xc_h_mean": 46.6,
    "xc_h_sd": 7,
    "correlation": 0.65,
    "sex": "F",
    "legend": "Females, White, 25 BMI 30, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 226,
    "n": 119,
    "r_h_mean": 351,
    "r_h_sd": 32,
    "xc_h_mean": 46.6,
    "xc_h_sd": 6.7,
    "correlation": 0.68,
    "sex": "F",
    "legend": "Females, White, 25 BMI 30, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 227,
    "n": 134,
    "r_h_mean": 353.1,
    "r_h_sd": 35.8,
    "xc_h_mean": 45.7,
    "xc_h_sd": 6.3,
    "correlation": 0.69,
    "sex": "F",
    "legend": "Females, White, 25 BMI 30, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 228,
    "n": 134,
    "r_h_mean": 353.1,
    "r_h_sd": 36.8,
    "xc_h_mean": 43.8,
    "xc_h_sd": 5.6,
    "correlation": 0.51,
    "sex": "F",
    "legend": "Females, White, 25 BMI 30, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 229,
    "n": 159,
    "r_h_mean": 362.1,
    "r_h_sd": 38.1,
    "xc_h_mean": 42.9,
    "xc_h_sd": 6.9,
    "correlation": 0.64,
    "sex": "F",
    "legend": "Females, White, 25 BMI 30, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 230,
    "n": 350,
    "r_h_mean": 329.1,
    "r_h_sd": 36.9,
    "xc_h_mean": 41.9,
    "xc_h_sd": 6.6,
    "correlation": 0.56,
    "sex": "F",
    "legend": "Females, White, 30 BMI 35, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 231,
    "n": 29,
    "r_h_mean": 333.8,
    "r_h_sd": 43.4,
    "xc_h_mean": 44.7,
    "xc_h_sd": 5.4,
    "correlation": 0.63,
    "sex": "F",
    "legend": "Females, White, 30 BMI 35, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 232,
    "n": 73,
    "r_h_mean": 318.5,
    "r_h_sd": 30.6,
    "xc_h_mean": 43.1,
    "xc_h_sd": 5.4,
    "correlation": 0.57,
    "sex": "F",
    "legend": "Females, White, 30 BMI 35, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 233,
    "n": 77,
    "r_h_mean": 326.8,
    "r_h_sd": 33.7,
    "xc_h_mean": 43.6,
    "xc_h_sd": 7.3,
    "correlation": 0.7,
    "sex": "F",
    "legend": "Females, White, 30 BMI 35, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 234,
    "n": 84,
    "r_h_mean": 330.1,
    "r_h_sd": 31.4,
    "xc_h_mean": 40.7,
    "xc_h_sd": 6.3,
    "correlation": 0.68,
    "sex": "F",
    "legend": "Females, White, 30 BMI 35, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 235,
    "n": 87,
    "r_h_mean": 337.3,
    "r_h_sd": 44.6,
    "xc_h_mean": 39.6,
    "xc_h_sd": 6.5,
    "correlation": 0.57,
    "sex": "F",
    "legend": "Females, White, 30 BMI 35, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 236,
    "n": 643,
    "r_h_mean": 297.5,
    "r_h_sd": 37.1,
    "xc_h_mean": 43,
    "xc_h_sd": 7.1,
    "correlation": 0.57,
    "sex": "M",
    "legend": "Males, Black, 19 BMI 25, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 237,
    "n": 217,
    "r_h_mean": 294.1,
    "r_h_sd": 33.4,
    "xc_h_mean": 45.4,
    "xc_h_sd": 6.8,
    "correlation": 0.66,
    "sex": "M",
    "legend": "Males, Black, 19 BMI 25, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 238,
    "n": 182,
    "r_h_mean": 290.9,
    "r_h_sd": 35.2,
    "xc_h_mean": 43.5,
    "xc_h_sd": 6.4,
    "correlation": 0.66,
    "sex": "M",
    "legend": "Males, Black, 19 BMI 25, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 239,
    "n": 115,
    "r_h_mean": 298.6,
    "r_h_sd": 35.9,
    "xc_h_mean": 42,
    "xc_h_sd": 6.3,
    "correlation": 0.7,
    "sex": "M",
    "legend": "Males, Black, 19 BMI 25, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 240,
    "n": 55,
    "r_h_mean": 309.8,
    "r_h_sd": 43.2,
    "xc_h_mean": 41.4,
    "xc_h_sd": 7.7,
    "correlation": 0.74,
    "sex": "M",
    "legend": "Males, Black, 19 BMI 25, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 241,
    "n": 74,
    "r_h_mean": 312.7,
    "r_h_sd": 43.3,
    "xc_h_mean": 38,
    "xc_h_sd": 7.5,
    "correlation": 0.68,
    "sex": "M",
    "legend": "Males, Black, 19 BMI 25, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 242,
    "n": 611,
    "r_h_mean": 267.5,
    "r_h_sd": 30.8,
    "xc_h_mean": 39.7,
    "xc_h_sd": 6.5,
    "correlation": 0.65,
    "sex": "M",
    "legend": "Males, Black, 25 BMI 30, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 243,
    "n": 141,
    "r_h_mean": 264.2,
    "r_h_sd": 29.7,
    "xc_h_mean": 41.5,
    "xc_h_sd": 6.1,
    "correlation": 0.74,
    "sex": "M",
    "legend": "Males, Black, 25 BMI 30, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 244,
    "n": 153,
    "r_h_mean": 264.7,
    "r_h_sd": 31.1,
    "xc_h_mean": 40.8,
    "xc_h_sd": 6,
    "correlation": 0.72,
    "sex": "M",
    "legend": "Males, Black, 25 BMI 30, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 245,
    "n": 139,
    "r_h_mean": 268.6,
    "r_h_sd": 27.3,
    "xc_h_mean": 40.6,
    "xc_h_sd": 6.5,
    "correlation": 0.67,
    "sex": "M",
    "legend": "Males, Black, 25 BMI 30, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 246,
    "n": 78,
    "r_h_mean": 267.5,
    "r_h_sd": 32.2,
    "xc_h_mean": 37.3,
    "xc_h_sd": 5.7,
    "correlation": 0.72,
    "sex": "M",
    "legend": "Males, Black, 25 BMI 30, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 247,
    "n": 100,
    "r_h_mean": 275,
    "r_h_sd": 34.5,
    "xc_h_mean": 36.4,
    "xc_h_sd": 7.1,
    "correlation": 0.73,
    "sex": "M",
    "legend": "Males, Black, 25 BMI 30, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 248,
    "n": 293,
    "r_h_mean": 246.4,
    "r_h_sd": 29.9,
    "xc_h_mean": 36.6,
    "xc_h_sd": 6.4,
    "correlation": 0.65,
    "sex": "M",
    "legend": "Males, Black, 30 BMI 35, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 249,
    "n": 66,
    "r_h_mean": 246.4,
    "r_h_sd": 32.8,
    "xc_h_mean": 39.6,
    "xc_h_sd": 5.8,
    "correlation": 0.65,
    "sex": "M",
    "legend": "Males, Black, 30 BMI 35, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 250,
    "n": 77,
    "r_h_mean": 243.1,
    "r_h_sd": 30.4,
    "xc_h_mean": 38.1,
    "xc_h_sd": 5.7,
    "correlation": 0.8,
    "sex": "M",
    "legend": "Males, Black, 30 BMI 35, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 251,
    "n": 57,
    "r_h_mean": 252.3,
    "r_h_sd": 27.9,
    "xc_h_mean": 38.1,
    "xc_h_sd": 5.7,
    "correlation": 0.8,
    "sex": "M",
    "legend": "Males, Black, 30 BMI 35, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 252,
    "n": 37,
    "r_h_mean": 244.3,
    "r_h_sd": 21.3,
    "xc_h_mean": 32.9,
    "xc_h_sd": 4.8,
    "correlation": 0.69,
    "sex": "M",
    "legend": "Males, Black, 30 BMI 35, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 253,
    "n": 56,
    "r_h_mean": 246.2,
    "r_h_sd": 32.3,
    "xc_h_mean": 32,
    "xc_h_sd": 6,
    "correlation": 0.72,
    "sex": "M",
    "legend": "Males, Black, 30 BMI 35, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 254,
    "n": 528,
    "r_h_mean": 392,
    "r_h_sd": 45.2,
    "xc_h_mean": 52.8,
    "xc_h_sd": 8.5,
    "correlation": 0.66,
    "sex": "F",
    "legend": "Females, Black, 19 BMI 25, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 255,
    "n": 207,
    "r_h_mean": 388.9,
    "r_h_sd": 48.6,
    "xc_h_mean": 53.9,
    "xc_h_sd": 8.7,
    "correlation": 0.76,
    "sex": "F",
    "legend": "Females, Black, 19 BMI 25, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 256,
    "n": 167,
    "r_h_mean": 387.1,
    "r_h_sd": 37.4,
    "xc_h_mean": 52.6,
    "xc_h_sd": 7.6,
    "correlation": 0.62,
    "sex": "F",
    "legend": "Females, Black, 19 BMI 25, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 257,
    "n": 75,
    "r_h_mean": 396.3,
    "r_h_sd": 44.9,
    "xc_h_mean": 54.2,
    "xc_h_sd": 8.4,
    "correlation": 0.7,
    "sex": "F",
    "legend": "Females, Black, 19 BMI 25, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 258,
    "n": 35,
    "r_h_mean": 398.2,
    "r_h_sd": 46.2,
    "xc_h_mean": 48.8,
    "xc_h_sd": 8.9,
    "correlation": 0.85,
    "sex": "F",
    "legend": "Females, Black, 19 BMI 25, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 259,
    "n": 44,
    "r_h_mean": 412.2,
    "r_h_sd": 50.7,
    "xc_h_mean": 49.8,
    "xc_h_sd": 9.4,
    "correlation": 0.51,
    "sex": "F",
    "legend": "Females, Black, 19 BMI 25, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 260,
    "n": 571,
    "r_h_mean": 354.6,
    "r_h_sd": 38.4,
    "xc_h_mean": 48.5,
    "xc_h_sd": 7.3,
    "correlation": 0.67,
    "sex": "F",
    "legend": "Females, Black, 25 BMI 30, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 261,
    "n": 146,
    "r_h_mean": 349.8,
    "r_h_sd": 37.5,
    "xc_h_mean": 49.3,
    "xc_h_sd": 7.5,
    "correlation": 0.75,
    "sex": "F",
    "legend": "Females, Black, 25 BMI 30, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 262,
    "n": 155,
    "r_h_mean": 355.5,
    "r_h_sd": 36.6,
    "xc_h_mean": 50.4,
    "xc_h_sd": 7,
    "correlation": 0.73,
    "sex": "F",
    "legend": "Females, Black, 25 BMI 30, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 263,
    "n": 125,
    "r_h_mean": 349.3,
    "r_h_sd": 36.3,
    "xc_h_mean": 47.6,
    "xc_h_sd": 6.7,
    "correlation": 0.68,
    "sex": "F",
    "legend": "Females, Black, 25 BMI 30, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 264,
    "n": 61,
    "r_h_mean": 358.9,
    "r_h_sd": 40,
    "xc_h_mean": 47.1,
    "xc_h_sd": 7.2,
    "correlation": 0.75,
    "sex": "F",
    "legend": "Females, Black, 25 BMI 30, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 265,
    "n": 84,
    "r_h_mean": 365.9,
    "r_h_sd": 42.9,
    "xc_h_mean": 45.9,
    "xc_h_sd": 7.6,
    "correlation": 0.65,
    "sex": "F",
    "legend": "Females, Black, 25 BMI 30, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 266,
    "n": 411,
    "r_h_mean": 328.6,
    "r_h_sd": 38.7,
    "xc_h_mean": 45.3,
    "xc_h_sd": 7.6,
    "correlation": 0.59,
    "sex": "F",
    "legend": "Females, Black, 30 BMI 35, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 267,
    "n": 75,
    "r_h_mean": 334.3,
    "r_h_sd": 32,
    "xc_h_mean": 48.8,
    "xc_h_sd": 5.7,
    "correlation": 0.49,
    "sex": "F",
    "legend": "Females, Black, 30 BMI 35, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 268,
    "n": 103,
    "r_h_mean": 328.6,
    "r_h_sd": 42.3,
    "xc_h_mean": 47.1,
    "xc_h_sd": 8,
    "correlation": 0.68,
    "sex": "F",
    "legend": "Females, Black, 30 BMI 35, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 269,
    "n": 93,
    "r_h_mean": 320.8,
    "r_h_sd": 37.7,
    "xc_h_mean": 45,
    "xc_h_sd": 7,
    "correlation": 0.65,
    "sex": "F",
    "legend": "Females, Black, 30 BMI 35, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 270,
    "n": 68,
    "r_h_mean": 327.4,
    "r_h_sd": 40.9,
    "xc_h_mean": 42.9,
    "xc_h_sd": 8,
    "correlation": 0.54,
    "sex": "F",
    "legend": "Females, Black, 30 BMI 35, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 271,
    "n": 72,
    "r_h_mean": 333.8,
    "r_h_sd": 38.2,
    "xc_h_mean": 41.9,
    "xc_h_sd": 6.7,
    "correlation": 0.66,
    "sex": "F",
    "legend": "Females, Black, 30 BMI 35, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 272,
    "n": 554,
    "r_h_mean": 310.3,
    "r_h_sd": 34.7,
    "xc_h_mean": 44.7,
    "xc_h_sd": 6.7,
    "correlation": 0.61,
    "sex": "M",
    "legend": "Males, Mexican American, 19 BMI 25, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 273,
    "n": 288,
    "r_h_mean": 309.4,
    "r_h_sd": 35.9,
    "xc_h_mean": 46.6,
    "xc_h_sd": 6.3,
    "correlation": 0.73,
    "sex": "M",
    "legend": "Males, Mexican American, 19 BMI 25, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 274,
    "n": 119,
    "r_h_mean": 308,
    "r_h_sd": 31.5,
    "xc_h_mean": 45,
    "xc_h_sd": 5.6,
    "correlation": 0.65,
    "sex": "M",
    "legend": "Males, Mexican American, 19 BMI 25, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 275,
    "n": 53,
    "r_h_mean": 307.4,
    "r_h_sd": 28.5,
    "xc_h_mean": 43.2,
    "xc_h_sd": 6.4,
    "correlation": 0.66,
    "sex": "M",
    "legend": "Males, Mexican American, 19 BMI 25, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 276,
    "n": 29,
    "r_h_mean": 317.7,
    "r_h_sd": 30,
    "xc_h_mean": 42.2,
    "xc_h_sd": 5.4,
    "correlation": 0.55,
    "sex": "M",
    "legend": "Males, Mexican American, 19 BMI 25, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 277,
    "n": 65,
    "r_h_mean": 318.3,
    "r_h_sd": 40.6,
    "xc_h_mean": 38.5,
    "xc_h_sd": 6.6,
    "correlation": 0.69,
    "sex": "M",
    "legend": "Males, Mexican American, 19 BMI 25, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 278,
    "n": 846,
    "r_h_mean": 281.9,
    "r_h_sd": 32.8,
    "xc_h_mean": 40.6,
    "xc_h_sd": 6.1,
    "correlation": 0.56,
    "sex": "M",
    "legend": "Males, Mexican American, 25 BMI 30, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 279,
    "n": 239,
    "r_h_mean": 283.6,
    "r_h_sd": 30.2,
    "xc_h_mean": 43.3,
    "xc_h_sd": 5.6,
    "correlation": 0.69,
    "sex": "M",
    "legend": "Males, Mexican American, 25 BMI 30, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 280,
    "n": 224,
    "r_h_mean": 279.1,
    "r_h_sd": 32,
    "xc_h_mean": 41.6,
    "xc_h_sd": 5.5,
    "correlation": 0.72,
    "sex": "M",
    "legend": "Males, Mexican American, 25 BMI 30, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 281,
    "n": 174,
    "r_h_mean": 280,
    "r_h_sd": 34.9,
    "xc_h_mean": 40.1,
    "xc_h_sd": 5.8,
    "correlation": 0.47,
    "sex": "M",
    "legend": "Males, Mexican American, 25 BMI 30, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 282,
    "n": 67,
    "r_h_mean": 279.8,
    "r_h_sd": 32.5,
    "xc_h_mean": 38.2,
    "xc_h_sd": 6.2,
    "correlation": 0.59,
    "sex": "M",
    "legend": "Males, Mexican American, 25 BMI 30, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 283,
    "n": 142,
    "r_h_mean": 286.8,
    "r_h_sd": 35.1,
    "xc_h_mean": 36.3,
    "xc_h_sd": 5.7,
    "correlation": 0.6,
    "sex": "M",
    "legend": "Males, Mexican American, 25 BMI 30, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 284,
    "n": 373,
    "r_h_mean": 254.6,
    "r_h_sd": 27.1,
    "xc_h_mean": 36.2,
    "xc_h_sd": 6.2,
    "correlation": 0.64,
    "sex": "M",
    "legend": "Males, Mexican American, 30 BMI 35, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 285,
    "n": 77,
    "r_h_mean": 257,
    "r_h_sd": 26.5,
    "xc_h_mean": 39.7,
    "xc_h_sd": 5.5,
    "correlation": 0.76,
    "sex": "M",
    "legend": "Males, Mexican American, 30 BMI 35, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 286,
    "n": 65,
    "r_h_mean": 254.5,
    "r_h_sd": 29,
    "xc_h_mean": 38.9,
    "xc_h_sd": 5.1,
    "correlation": 0.78,
    "sex": "M",
    "legend": "Males, Mexican American, 30 BMI 35, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 287,
    "n": 95,
    "r_h_mean": 251.3,
    "r_h_sd": 25,
    "xc_h_mean": 36.3,
    "xc_h_sd": 5.7,
    "correlation": 0.79,
    "sex": "M",
    "legend": "Males, Mexican American, 30 BMI 35, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 288,
    "n": 54,
    "r_h_mean": 252.7,
    "r_h_sd": 28.8,
    "xc_h_mean": 34.2,
    "xc_h_sd": 5.7,
    "correlation": 0.7,
    "sex": "M",
    "legend": "Males, Mexican American, 30 BMI 35, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 289,
    "n": 82,
    "r_h_mean": 257.4,
    "r_h_sd": 27.6,
    "xc_h_mean": 31.9,
    "xc_h_sd": 5.2,
    "correlation": 0.66,
    "sex": "M",
    "legend": "Males, Mexican American, 30 BMI 35, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 290,
    "n": 475,
    "r_h_mean": 411.6,
    "r_h_sd": 44.4,
    "xc_h_mean": 53.2,
    "xc_h_sd": 7.7,
    "correlation": 0.66,
    "sex": "F",
    "legend": "Females, Mexican American, 19 BMI 25, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 291,
    "n": 219,
    "r_h_mean": 409.1,
    "r_h_sd": 43.9,
    "xc_h_mean": 54.2,
    "xc_h_sd": 7.4,
    "correlation": 0.68,
    "sex": "F",
    "legend": "Females, Mexican American, 19 BMI 25, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 292,
    "n": 122,
    "r_h_mean": 405.9,
    "r_h_sd": 41,
    "xc_h_mean": 53,
    "xc_h_sd": 7.3,
    "correlation": 0.72,
    "sex": "F",
    "legend": "Females, Mexican American, 19 BMI 25, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 293,
    "n": 56,
    "r_h_mean": 421.2,
    "r_h_sd": 49.9,
    "xc_h_mean": 54.4,
    "xc_h_sd": 7.8,
    "correlation": 0.78,
    "sex": "F",
    "legend": "Females, Mexican American, 19 BMI 25, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 294,
    "n": 29,
    "r_h_mean": 411.7,
    "r_h_sd": 48.4,
    "xc_h_mean": 48.9,
    "xc_h_sd": 7.5,
    "correlation": 0.72,
    "sex": "F",
    "legend": "Females, Mexican American, 19 BMI 25, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 295,
    "n": 49,
    "r_h_mean": 425.8,
    "r_h_sd": 43.1,
    "xc_h_mean": 49.9,
    "xc_h_sd": 8.8,
    "correlation": 0.63,
    "sex": "F",
    "legend": "Females, Mexican American, 19 BMI 25, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 296,
    "n": 597,
    "r_h_mean": 373.8,
    "r_h_sd": 39.5,
    "xc_h_mean": 49.4,
    "xc_h_sd": 7.8,
    "correlation": 0.6,
    "sex": "F",
    "legend": "Females, Mexican American, 25 BMI 30, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 297,
    "n": 157,
    "r_h_mean": 378.5,
    "r_h_sd": 42.6,
    "xc_h_mean": 52.3,
    "xc_h_sd": 7.8,
    "correlation": 0.74,
    "sex": "F",
    "legend": "Females, Mexican American, 25 BMI 30, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 298,
    "n": 160,
    "r_h_mean": 365.5,
    "r_h_sd": 36.9,
    "xc_h_mean": 50.2,
    "xc_h_sd": 6.5,
    "correlation": 0.64,
    "sex": "F",
    "legend": "Females, Mexican American, 25 BMI 30, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 299,
    "n": 124,
    "r_h_mean": 373.5,
    "r_h_sd": 37.9,
    "xc_h_mean": 49.8,
    "xc_h_sd": 7.1,
    "correlation": 0.62,
    "sex": "F",
    "legend": "Females, Mexican American, 25 BMI 30, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 300,
    "n": 53,
    "r_h_mean": 382.4,
    "r_h_sd": 40.5,
    "xc_h_mean": 47.8,
    "xc_h_sd": 7.5,
    "correlation": 0.67,
    "sex": "F",
    "legend": "Females, Mexican American, 25 BMI 30, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 301,
    "n": 103,
    "r_h_mean": 375.8,
    "r_h_sd": 38.4,
    "xc_h_mean": 44.3,
    "xc_h_sd": 7.9,
    "correlation": 0.56,
    "sex": "F",
    "legend": "Females, Mexican American, 25 BMI 30, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 302,
    "n": 404,
    "r_h_mean": 346.1,
    "r_h_sd": 37.2,
    "xc_h_mean": 45.4,
    "xc_h_sd": 7.1,
    "correlation": 0.6,
    "sex": "F",
    "legend": "Females, Mexican American, 30 BMI 35, 20 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 303,
    "n": 78,
    "r_h_mean": 347.8,
    "r_h_sd": 38.4,
    "xc_h_mean": 48.3,
    "xc_h_sd": 6.9,
    "correlation": 0.66,
    "sex": "F",
    "legend": "Females, Mexican American, 30 BMI 35, 20 age 29",
    "country": "USA",
    "age": "29",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 304,
    "n": 90,
    "r_h_mean": 345.1,
    "r_h_sd": 36.3,
    "xc_h_mean": 47.3,
    "xc_h_sd": 6.4,
    "correlation": 0.68,
    "sex": "F",
    "legend": "Females, Mexican American, 30 BMI 35, 30 age 39",
    "country": "USA",
    "age": "39",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 305,
    "n": 101,
    "r_h_mean": 345.5,
    "r_h_sd": 32.9,
    "xc_h_mean": 46.6,
    "xc_h_sd": 6.1,
    "correlation": 0.62,
    "sex": "F",
    "legend": "Females, Mexican American, 30 BMI 35, 40 age 49",
    "country": "USA",
    "age": "49",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 306,
    "n": 57,
    "r_h_mean": 344.8,
    "r_h_sd": 39,
    "xc_h_mean": 43.3,
    "xc_h_sd": 6.2,
    "correlation": 0.64,
    "sex": "F",
    "legend": "Females, Mexican American, 30 BMI 35, 50 age 59",
    "country": "USA",
    "age": "59",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 307,
    "n": 78,
    "r_h_mean": 347.2,
    "r_h_sd": 41.3,
    "xc_h_mean": 40.4,
    "xc_h_sd": 6.8,
    "correlation": 0.67,
    "sex": "F",
    "legend": "Females, Mexican American, 30 BMI 35, 60 age 69",
    "country": "USA",
    "age": "69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A et al, Nutrition 18:153-167, 2002. (see BIVAguide, ref. 23)",
    "source": "confidence"
  },
  {
    "code": 1,
    "n": 354,
    "r_h_mean": 298.6,
    "r_h_sd": 43.2,
    "xc_h_mean": 30.8,
    "xc_h_sd": 7.2,
    "correlation": 0.47,
    "sex": "M",
    "legend": "Males, White, 16 age 85 yr, 16 BMI 31, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "16–85",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "Piccoli A, Nigrelli S, Caberlotto A, Bottazzo S, Rossi B, Pillon L, Maggiore Q: Bivariate normal values of the bioelectrical impedance vector in adult and elderly populations. Am J Clin Nutr 61:269-270, 1995.",
    "source": "tolerance"
  },
  {
    "code": 2,
    "n": 372,
    "r_h_mean": 371.9,
    "r_h_sd": 49,
    "xc_h_mean": 34.4,
    "xc_h_sd": 7.7,
    "correlation": 0.41,
    "sex": "F",
    "legend": "Females, White, 16 age 85 yr, 16 BMI 31, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "16–85",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "Piccoli A, Nigrelli S, Caberlotto A, Bottazzo S, Rossi B, Pillon L, Maggiore Q: Bivariate normal values of the bioelectrical impedance vector in adult and elderly populations. Am J Clin Nutr 61:269-270, 1995.",
    "source": "tolerance"
  },
  {
    "code": 3,
    "n": 1572,
    "r_h_mean": 277.2,
    "r_h_sd": 33.6,
    "xc_h_mean": 38.1,
    "xc_h_sd": 6.2,
    "correlation": 0.6,
    "sex": "M",
    "legend": "Males, White, 20 age 69 yr, 19 BMI 30, USA (NHANES III), Valhalla Scientific",
    "country": "USA",
    "age": "20–69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A, Nigrelli S, Caberlotto A, Bottazzo S, Rossi B, Pillon L, Maggiore Q: Bivariate normal values of the bioelectrical impedance vector in adult and elderly populations. Am J Clin Nutr 61:269-270, 1995.",
    "source": "tolerance"
  },
  {
    "code": 4,
    "n": 1625,
    "r_h_mean": 372.9,
    "r_h_sd": 44,
    "xc_h_mean": 46.9,
    "xc_h_sd": 7.1,
    "correlation": 0.61,
    "sex": "F",
    "legend": "Females, White, 20 age 69 yr, 19 BMI 30, USA (NHANES III), Valhalla Scientific",
    "country": "USA",
    "age": "20–69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A, Nigrelli S, Caberlotto A, Bottazzo S, Rossi B, Pillon L, Maggiore Q: Bivariate normal values of the bioelectrical impedance vector in adult and elderly populations. Am J Clin Nutr 61:269-270, 1995.",
    "source": "tolerance"
  },
  {
    "code": 5,
    "n": 1254,
    "r_h_mean": 282.9,
    "r_h_sd": 37.3,
    "xc_h_mean": 41.4,
    "xc_h_sd": 7,
    "correlation": 0.63,
    "sex": "M",
    "legend": "Males, Black, 20 age 69 yr, 19 BMI 30, USA (NHANES III), Valhalla Scientific",
    "country": "USA",
    "age": "20–69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A, Nigrelli S, Caberlotto A, Bottazzo S, Rossi B, Pillon L, Maggiore Q: Bivariate normal values of the bioelectrical impedance vector in adult and elderly populations. Am J Clin Nutr 61:269-270, 1995.",
    "source": "tolerance"
  },
  {
    "code": 6,
    "n": 1099,
    "r_h_mean": 372.5,
    "r_h_sd": 45.8,
    "xc_h_mean": 50.6,
    "xc_h_sd": 8.2,
    "correlation": 0.69,
    "sex": "F",
    "legend": "Females, Black, 20 age 69 yr, 19 BMI 30, USA (NHANES III), Valhalla Scientific",
    "country": "USA",
    "age": "20–69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A, Nigrelli S, Caberlotto A, Bottazzo S, Rossi B, Pillon L, Maggiore Q: Bivariate normal values of the bioelectrical impedance vector in adult and elderly populations. Am J Clin Nutr 61:269-270, 1995.",
    "source": "tolerance"
  },
  {
    "code": 7,
    "n": 1400,
    "r_h_mean": 293.1,
    "r_h_sd": 36.3,
    "xc_h_mean": 42.2,
    "xc_h_sd": 6.7,
    "correlation": 0.62,
    "sex": "M",
    "legend": "Males, Mexican American, 20 age 69 yr, 19 BMI 30, USA (NHANES III), Valhalla Scientific",
    "country": "USA",
    "age": "20–69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A, Nigrelli S, Caberlotto A, Bottazzo S, Rossi B, Pillon L, Maggiore Q: Bivariate normal values of the bioelectrical impedance vector in adult and elderly populations. Am J Clin Nutr 61:269-270, 1995.",
    "source": "tolerance"
  },
  {
    "code": 8,
    "n": 1072,
    "r_h_mean": 390.6,
    "r_h_sd": 45.8,
    "xc_h_mean": 51.1,
    "xc_h_sd": 8,
    "correlation": 0.65,
    "sex": "F",
    "legend": "Females, Mexican American, 20 age 69 yr, 19 BMI 30, USA (NHANES III), Valhalla Scientific",
    "country": "USA",
    "age": "20–69",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Piccoli A, Nigrelli S, Caberlotto A, Bottazzo S, Rossi B, Pillon L, Maggiore Q: Bivariate normal values of the bioelectrical impedance vector in adult and elderly populations. Am J Clin Nutr 61:269-270, 1995.",
    "source": "tolerance"
  },
  {
    "code": 9,
    "n": 161,
    "r_h_mean": 276,
    "r_h_sd": 35.4,
    "xc_h_mean": 28.9,
    "xc_h_sd": 9.2,
    "correlation": 0.638,
    "sex": "M",
    "legend": "Males, White, age 78 yr, BMI 28, USA (FHS), RJL Systems",
    "country": "USA",
    "age": "78",
    "equipment": "RJL Systems",
    "population": "Healthy",
    "reference": "Roubenoff R, Baumgartner RN, Harris TB, Dallal GE, Hannan MT, Economos CD, Stauber PM, Wilson PWF, Kiel DP: Application of bioelectrical impedance analysis to elderly populations. J Gerontol Med Sci 52A:M129-M136, 1997.",
    "source": "tolerance"
  },
  {
    "code": 10,
    "n": 294,
    "r_h_mean": 362.4,
    "r_h_sd": 45.6,
    "xc_h_mean": 32.8,
    "xc_h_sd": 8.1,
    "correlation": 0.638,
    "sex": "F",
    "legend": "Females, White, age 78 yr, BMI 27, USA (FHS), RJL Systems",
    "country": "USA",
    "age": "78",
    "equipment": "RJL Systems",
    "population": "Healthy",
    "reference": "Roubenoff R, Baumgartner RN, Harris TB, Dallal GE, Hannan MT, Economos CD, Stauber PM, Wilson PWF, Kiel DP: Application of bioelectrical impedance analysis to elderly populations. J Gerontol Med Sci 52A:M129-M136, 1997.",
    "source": "tolerance"
  },
  {
    "code": 11,
    "n": 116,
    "r_h_mean": 286.8,
    "r_h_sd": 31.6,
    "xc_h_mean": 27.4,
    "xc_h_sd": 4.2,
    "correlation": 0.638,
    "sex": "M",
    "legend": "Males, White, age 76 yr, BMI 26, USA (NMAPS), BCA",
    "country": "USA",
    "age": "76",
    "equipment": "BCA",
    "population": "Healthy",
    "reference": "Roubenoff R, Baumgartner RN, Harris TB, Dallal GE, Hannan MT, Economos CD, Stauber PM, Wilson PWF, Kiel DP: Application of bioelectrical impedance analysis to elderly populations. J Gerontol Med Sci 52A:M129-M136, 1997.",
    "source": "tolerance"
  },
  {
    "code": 12,
    "n": 167,
    "r_h_mean": 386.3,
    "r_h_sd": 38.1,
    "xc_h_mean": 34.1,
    "xc_h_sd": 4.9,
    "correlation": 0.638,
    "sex": "F",
    "legend": "Females, White, age 76 yr, BMI 25, USA (NMAPS), BCA",
    "country": "USA",
    "age": "76",
    "equipment": "BCA",
    "population": "Healthy",
    "reference": "Roubenoff R, Baumgartner RN, Harris TB, Dallal GE, Hannan MT, Economos CD, Stauber PM, Wilson PWF, Kiel DP: Application of bioelectrical impedance analysis to elderly populations. J Gerontol Med Sci 52A:M129-M136, 1997.",
    "source": "tolerance"
  },
  {
    "code": 13,
    "n": 151,
    "r_h_mean": 388.5,
    "r_h_sd": 44.1,
    "xc_h_mean": 50.8,
    "xc_h_sd": 6.9,
    "correlation": 0.638,
    "sex": "F",
    "legend": "Females, Mexican American, 18 age 60 yr, 17 BMI 38, USA, Valhalla Scientific",
    "country": "USA",
    "age": "18–60",
    "equipment": "Valhalla Scientific",
    "population": "Healthy",
    "reference": "Stolarczyk LM, Heyward VH, Hicks VL, Baumgartner RN: Predictive accuracy of bioelectrical impedance in stimating body composition of Native American women. Am J Clin Nutr 59:964-970, 1994. [Valhalla readings: see above. Correlation coefficient not reported; r=0.64 estimated in 8,022 subjects, USA, NHANES III study (details in reference 23, BIVAguide)].",
    "source": "tolerance"
  },
  {
    "code": 100,
    "n": 163,
    "r_h_mean": 1002,
    "r_h_sd": 128,
    "xc_h_mean": 85,
    "xc_h_sd": 27,
    "correlation": 0.31,
    "sex": "M",
    "legend": "Males + Females, White, 1 age 7 days, BMI 13, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "1–7",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "Piccoli A, Fanos V, Peruzzi L, Schena S, Pizzini C, Borgione S, Bertino E, Chiaffoni G, Coppo R, Tatò L: Reference values of the bioelectical impedance vector in neonates in the first week after birdth. Nutrition 18:17-21, 2002. [Remark: no gender influence on impedance. Gender is required by graphic procedures]",
    "source": "tolerance"
  },
  {
    "code": 101,
    "n": 163,
    "r_h_mean": 1002,
    "r_h_sd": 128,
    "xc_h_mean": 85,
    "xc_h_sd": 27,
    "correlation": 0.31,
    "sex": "F",
    "legend": "Females + Females, White, 1 age 7 days, BMI 13, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "1–7",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "Piccoli A, Fanos V, Peruzzi L, Schena S, Pizzini C, Borgione S, Bertino E, Chiaffoni G, Coppo R, Tatò L: Reference values of the bioelectical impedance vector in neonates in the first week after birdth. Nutrition 18:17-21, 2002. [Remark: no gender influence on impedance. Gender is required by graphic procedures]",
    "source": "tolerance"
  },
  {
    "code": 102,
    "n": 115,
    "r_h_mean": 751,
    "r_h_sd": 75,
    "xc_h_mean": 60,
    "xc_h_sd": 10,
    "correlation": 0.41,
    "sex": "M",
    "legend": "Males + Females, White, 2 age 3 yr, BMI 16, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "2–3",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 103,
    "n": 115,
    "r_h_mean": 751,
    "r_h_sd": 75,
    "xc_h_mean": 60,
    "xc_h_sd": 10,
    "correlation": 0.41,
    "sex": "F",
    "legend": "Males + Females, White, 2 age 3 yr, BMI 16, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "2–3",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 104,
    "n": 220,
    "r_h_mean": 672,
    "r_h_sd": 72,
    "xc_h_mean": 58,
    "xc_h_sd": 8,
    "correlation": 0.57,
    "sex": "M",
    "legend": "Males + Females, White, 4 age 5 yr, BMI 16, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "4–5",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 105,
    "n": 220,
    "r_h_mean": 672,
    "r_h_sd": 72,
    "xc_h_mean": 58,
    "xc_h_sd": 8,
    "correlation": 0.57,
    "sex": "F",
    "legend": "Males + Females, White, 4 age 5 yr, BMI 16, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "4–5",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 106,
    "n": 448,
    "r_h_mean": 600,
    "r_h_sd": 64,
    "xc_h_mean": 56,
    "xc_h_sd": 7,
    "correlation": 0.56,
    "sex": "M",
    "legend": "Males + Females, White, 6 age 7 yr, BMI 16, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "6–7",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 107,
    "n": 448,
    "r_h_mean": 600,
    "r_h_sd": 64,
    "xc_h_mean": 56,
    "xc_h_sd": 7,
    "correlation": 0.56,
    "sex": "F",
    "legend": "Males + Females, White, 6 age 7 yr, BMI 16, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "6–7",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 108,
    "n": 227,
    "r_h_mean": 561,
    "r_h_sd": 58,
    "xc_h_mean": 54,
    "xc_h_sd": 7,
    "correlation": 0.57,
    "sex": "M",
    "legend": "Males + Females, White, age 8 yr, BMI 16, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "8",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 109,
    "n": 227,
    "r_h_mean": 561,
    "r_h_sd": 58,
    "xc_h_mean": 54,
    "xc_h_sd": 7,
    "correlation": 0.57,
    "sex": "F",
    "legend": "Males + Females, White, age 8 yr, BMI 16, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "8",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 110,
    "n": 200,
    "r_h_mean": 527,
    "r_h_sd": 53,
    "xc_h_mean": 52,
    "xc_h_sd": 7,
    "correlation": 0.66,
    "sex": "M",
    "legend": "Males + Females, White, age 9 yr, BMI 16, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "9",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 111,
    "n": 200,
    "r_h_mean": 527,
    "r_h_sd": 53,
    "xc_h_mean": 52,
    "xc_h_sd": 7,
    "correlation": 0.66,
    "sex": "F",
    "legend": "Males + Females, White, age 9 yr, BMI 16, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "9",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 112,
    "n": 369,
    "r_h_mean": 486,
    "r_h_sd": 58,
    "xc_h_mean": 48,
    "xc_h_sd": 6,
    "correlation": 0.71,
    "sex": "M",
    "legend": "Males + Females, White, 10 age 11 yr, BMI 17, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "10–11",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 113,
    "n": 369,
    "r_h_mean": 486,
    "r_h_sd": 58,
    "xc_h_mean": 48,
    "xc_h_sd": 6,
    "correlation": 0.71,
    "sex": "F",
    "legend": "Males + Females, White, 10 age 11 yr, BMI 17, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "10–11",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 114,
    "n": 132,
    "r_h_mean": 440,
    "r_h_sd": 57,
    "xc_h_mean": 44,
    "xc_h_sd": 6,
    "correlation": 0.77,
    "sex": "M",
    "legend": "Males + Females, White, age 12 yr, BMI 18, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "12",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 115,
    "n": 132,
    "r_h_mean": 440,
    "r_h_sd": 57,
    "xc_h_mean": 44,
    "xc_h_sd": 6,
    "correlation": 0.77,
    "sex": "F",
    "legend": "Males + Females, White, age 12 yr, BMI 18, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "12",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 116,
    "n": 116,
    "r_h_mean": 402,
    "r_h_sd": 61,
    "xc_h_mean": 42,
    "xc_h_sd": 6,
    "correlation": 0.74,
    "sex": "M",
    "legend": "Males + Females, White, age 13 yr, BMI 19, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "13",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 117,
    "n": 116,
    "r_h_mean": 402,
    "r_h_sd": 61,
    "xc_h_mean": 42,
    "xc_h_sd": 6,
    "correlation": 0.74,
    "sex": "F",
    "legend": "Males + Females, White, age 13 yr, BMI 19, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "13",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 118,
    "n": 97,
    "r_h_mean": 338,
    "r_h_sd": 48,
    "xc_h_mean": 37,
    "xc_h_sd": 5,
    "correlation": 0.67,
    "sex": "M",
    "legend": "Males, White, 14 age 15 yr, BMI 20, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "14–15",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  },
  {
    "code": 119,
    "n": 120,
    "r_h_mean": 403,
    "r_h_sd": 44,
    "xc_h_mean": 41,
    "xc_h_sd": 6,
    "correlation": 0.67,
    "sex": "F",
    "legend": "Females, White, 14 age 15 yr, BMI 21, Italy, Akern-RJL Systems",
    "country": "Italy",
    "age": "14–15",
    "equipment": "Akern-RJL Systems",
    "population": "Healthy",
    "reference": "De Palo T, Messina G, Edefonti A, Perfumo F, Pisanello L, Peruzzi L, Di Iorio B, Mignozzi M, Vienna A, Conti G, Penza R, Piccoli A: Normal values of the bioelectrical impedance vector in childwhood and puberty. Nutrition 16:417-424, 2000. [Remark: no gender influence on impedance untill 14 yr. Gender is required by graphic procedures.]",
    "source": "tolerance"
  }
];

window.BIVA2_PAIRED_REFERENCES = [
  {
    "code": 101,
    "n": 680,
    "dr_h_mean": 50.4,
    "dr_h_sd": 18.2,
    "dxc_h_mean": 9.1,
    "dxc_h_sd": 4.8,
    "correlation": 0.553,
    "sex": "M",
    "legend": "Males, White, post-pre Stable HD session, - 2.8 Kg",
    "country": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A, Kidney Int 53:1036-1043, 1998. (see Groups sheet)",
    "source": "paired"
  },
  {
    "code": 102,
    "n": 436,
    "dr_h_mean": 64.86,
    "dr_h_sd": 23.3,
    "dxc_h_mean": 10.4,
    "dxc_h_sd": 5.4,
    "correlation": 0.6,
    "sex": "F",
    "legend": "Females, White, post-pre Stable HD session, -2.6 Kg",
    "country": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A, Kidney Int 53:1036-1043, 1998. (see Groups sheet)",
    "source": "paired"
  },
  {
    "code": 103,
    "n": 118,
    "dr_h_mean": 49.25,
    "dr_h_sd": 17.5,
    "dxc_h_mean": 6.8,
    "dxc_h_sd": 4.8,
    "correlation": 0.62,
    "sex": "M",
    "legend": "Males, White, post-pre Unstable HD session, -2.9 Kg",
    "country": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A, Kidney Int 53:1036-1043, 1998. (see Groups sheet)",
    "source": "paired"
  },
  {
    "code": 104,
    "n": 133,
    "dr_h_mean": 61.7,
    "dr_h_sd": 26.25,
    "dxc_h_mean": 8.9,
    "dxc_h_sd": 5.6,
    "correlation": 0.591,
    "sex": "F",
    "legend": "Females, White, post-pre Unstable HD session, -2.4 Kg",
    "country": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A, Kidney Int 53:1036-1043, 1998. (see Groups sheet)",
    "source": "paired"
  },
  {
    "code": 110,
    "n": 18,
    "dr_h_mean": 9.8,
    "dr_h_sd": 19.2,
    "dxc_h_mean": 0.7,
    "dxc_h_sd": 4.8,
    "correlation": 0.24,
    "sex": "M",
    "legend": "Males, White, Obesity II-III, post-pre diet, -10.9 Kg",
    "country": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see Groups sheet)",
    "source": "paired"
  },
  {
    "code": 111,
    "n": 30,
    "dr_h_mean": -3.1,
    "dr_h_sd": 28.5,
    "dxc_h_mean": -0.3,
    "dxc_h_sd": 4.9,
    "correlation": 0.59,
    "sex": "F",
    "legend": "Females, White, Obesity III, post-pre diet, -7.3 Kg",
    "country": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see Groups sheet)",
    "source": "paired"
  },
  {
    "code": 112,
    "n": 13,
    "dr_h_mean": 49,
    "dr_h_sd": 16.5,
    "dxc_h_mean": 8.6,
    "dxc_h_sd": 3.2,
    "correlation": 0.67,
    "sex": "M",
    "legend": "Males, White, Obesity I-III, post-pre HD, -3.6 Kg",
    "country": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see Groups sheet)",
    "source": "paired"
  },
  {
    "code": 113,
    "n": 19,
    "dr_h_mean": 62,
    "dr_h_sd": 19.7,
    "dxc_h_mean": 9.3,
    "dxc_h_sd": 5.4,
    "correlation": 0.48,
    "sex": "F",
    "legend": "Females, White, Obesity I-II, post-pre HD, -2.9 Kg",
    "country": "—",
    "equipment": "Akern-RJL Systems",
    "population": "Clinical",
    "reference": "Piccoli A et al, Int J Obes 22:97-104, 1998. (see Groups sheet)",
    "source": "paired"
  }
];
